-- First
CREATE DATABASE TwitterDB;

USE TwitterDB;
GO

CREATE TABLE Users (
    UserId INT IDENTITY(1,1),
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL PRIMARY KEY,
    BirthMonth VARCHAR(25) NOT NULL,
    BirthDay INT NOT NULL CHECK (BirthDay BETWEEN 1 AND 31),
    BirthYear INT NOT NULL CHECK (BirthYear BETWEEN 1900 AND YEAR(GETDATE())),
    Username VARCHAR(100),
    Password VARCHAR(100)
);
GO

GO

ALTER TABLE Users
ADD ProfilePicture VARCHAR(300) NULL,
    CoverPicture VARCHAR(300) NULL,
    Bio NVARCHAR(160) NULL;
GO

-- localhost\SQLEXPRESS